# Generated by Django 6.0.5 on 2026-05-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
