# Generated by Django 6.0.5 on 2026-05-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualaccount',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='virtualaccount',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='virtualaccount',
            name='squad_customer_identifier',
        ),
        migrations.RemoveField(
            model_name='virtualaccount',
            name='squad_virtual_account_id',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='is_active',
        ),
        migrations.AddField(
            model_name='virtualaccount',
            name='address',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='virtualaccount',
            name='bank_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='virtualaccount',
            name='beneficiary_account',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='virtualaccount',
            name='bvn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='virtualaccount',
            name='customer_identifier',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='virtualaccount',
            name='dob',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='virtualaccount',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='virtualaccount',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='virtualaccount',
            name='gender',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='virtualaccount',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='virtualaccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='virtualaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
