name: Django Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "Backend/**"

  pull_request:
    branches:
      - main
    paths:
      - "Backend/**"

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v3

      - name: Setup Python
        run: uv python install 3.12

      - name: Install Dependencies
        run: uv sync

      - name: Run Migrations
        run: uv run python manage.py migrate

      - name: Run Tests
        run: uv run python manage.py test