name: Full Stack CI/CD

on:
  push:
    branches:
      - master
    paths:
      - "Backend/**"
      - "Frontend/**"

  pull_request:
    branches:
      - main
    paths:
      - "Backend/**"
      - "Frontend/**"

jobs:
  backend-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v3

      - name: Setup Python
        run: uv python install 3.12

      - name: Install Dependencies
        run: uv sync

      - name: Run migrations
        env:
          SQUAD_SECRET_KEY: ${{ secrets.SQUAD_SECRET_KEY }}
        run: uv run python manage.py migrate

      - name: Run Tests
        run: uv run python manage.py test

  frontend-build:
    name: React Frontend CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build Project
        run: npm run build
